# .github/workflows/check-rules.yml
---
name: Check Rules
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'rules/**/*.yml'
    pull_request:
      branches: [ main ]

jobs:
  lint-sigma-rules:
    name: Lint Sigma Rules
    runs-on: ubuntu-latest
    container:
      image: pipelinecomponents/yamllint
      volumes:
        - rules:/rules
    steps:
      - name: Lint YAML rules
        run: |
          yamllint -d relaxed /rules
  
  check-sigma-rules:
    name: Check Sigma Rules
    runs-on: ubuntu-latest
    container:
      image: python:3.11
      volumes:
        - rules:/rules
    steps:
      - name: Install sigma-cli
        run: |
          pip install sigma-cli
      - name: sigma-cli check
        run: |
          sigma check -i /rules
