# bitbucket-pipelines.yml
---
options:
  docker: true
  max-time: 20

pipelines:
  default:
    - stage:
        name: check-rules
        condition:
          # Only run this stage if YAML files in rules/ are in a changeset
          changesets:
            includePaths:
              - "bitbucket-pipelines.yml"
              - "rules/**/*.yml"
        steps:
          - step:
              runs-on: self.hosted
              name: lint-yaml-rules
              image: pipelinecomponents/yamllint:latest
              script:
                - yamllint -d relaxed rules/
          - step:
              runs-on: self.hosted
              name: check-sigma-rules
              image: python:3.11
              script:
                - python -m pip install sigma-cli
                - sigma check -i rules/

